# Generated by Django 6.1.1 on 2026-10-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('company', models.CharField(blank=True, default='', max_length=150)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GENERAL', 'General & Operations'), ('QUOTATIONS', 'Quotations & Bulk RFQ'), ('SHIPPING', 'Shipping, Incoterms & Customs'), ('TECHNICAL', 'Technical & Certifications'), ('WARRANTY', 'Warranties & Support')], default='GENERAL', max_length=30)),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'category', 'question'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('designation', models.CharField(max_length=150)),
                ('department', models.CharField(choices=[('MANAGEMENT', 'Executive Leadership'), ('SALES', 'International Sales & RFQ'), ('EXPORT', 'Export Logistics & Trade'), ('TECHNICAL', 'Solar Technical & Engineering'), ('SUPPORT', 'Client Support & Quality Desk')], default='SALES', max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/team/')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('bio', models.TextField()),
                ('social_linkedin', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'department', 'name'],
            },
        ),
    ]
