# Generated by Django 6.1.1 on 2026-10-04 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_product_datasheet_pdf_product_in_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('company_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('COMMERCIAL', 'Commercial & Industrial (C&I Rooftop)'), ('UTILITY', 'Utility Scale Solar Farm (Ground Mount)'), ('RESIDENTIAL', 'Residential / Housing Community'), ('OFF_GRID', 'Off-Grid & Hybrid Microgrid'), ('AGRICULTURE', 'Agricultural Solar Pumping & Irrigation'), ('DISTRIBUTION', 'Wholesale Resale / Regional Distribution')], default='COMMERCIAL', max_length=30)),
                ('required_capacity', models.CharField(help_text='e.g., 550 kWp, 5 MW, 10 Containers', max_length=100)),
                ('project_location', models.CharField(help_text='City, State/Province, Country', max_length=200)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('shipping_destination', models.CharField(help_text='Destination Seaport or Final Delivery City', max_length=200)),
                ('preferred_incoterm', models.CharField(default='CIF', help_text='e.g., FOB, CIF, DDP, EXW', max_length=20)),
                ('message', models.TextField(help_text='Detailed specifications, technical constraints, or bill of quantities.')),
                ('attachment', models.FileField(blank=True, help_text='Tender doc, single-line diagram, or BoQ (PDF/Excel)', null=True, upload_to='enquiries/attachments/')),
                ('status', models.CharField(choices=[('REQUESTED', 'Enquiry Submitted'), ('ASSIGNED', 'Sales Executive Assigned'), ('UNDER_REVIEW', 'Requirements Reviewed'), ('QUOTATION_PREPARED', 'Quotation Prepared'), ('QUOTATION_SENT', 'Quotation Sent'), ('NEGOTIATION', 'Buyer Review & Negotiation'), ('APPROVED', 'Order Confirmed (Won)'), ('REJECTED', 'Rejected / Closed'), ('CLOSED', 'Archived / Closed')], default='REQUESTED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_sales_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Enquiry',
                'verbose_name_plural': 'Project Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('target_price_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Optional target unit price in USD', max_digits=10, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=250)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='enquiries.enquiry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_lines', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Enquiry Item',
                'verbose_name_plural': 'Enquiry Items',
            },
        ),
        migrations.CreateModel(
            name='EnquiryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='enquiries.enquiry')),
            ],
            options={
                'verbose_name': 'Enquiry Status Log',
                'verbose_name_plural': 'Enquiry Status Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('incoterm', models.CharField(default='CIF', max_length=20)),
                ('payment_terms', models.CharField(default='30% T/T Advance, 70% against Bill of Lading', max_length=150)),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Buyer'), ('ACCEPTED', 'Accepted by Buyer'), ('NEGOTIATING', 'Buyer Requested Revision'), ('DECLINED', 'Declined by Buyer'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=30)),
                ('sales_rep_notes', models.TextField(blank=True, default='')),
                ('buyer_feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='enquiries.enquiry')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commercial Quotation',
                'verbose_name_plural': 'Commercial Quotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('specifications_summary', models.CharField(blank=True, default='', max_length=250)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='enquiries.quotation')),
            ],
        ),
    ]
