# Generated by Django 6.1.1 on 2026-10-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='ISO 2-letter Country Code (e.g. AE, SA, DE, AU)', max_length=5, unique=True)),
                ('region', models.CharField(help_text='e.g., Middle East & GCC, Europe, Africa, Asia-Pacific', max_length=80)),
                ('flag_emoji', models.CharField(blank=True, default='🌐', max_length=10)),
                ('primary_ports', models.CharField(blank=True, default='', help_text='Major container ports (e.g., Jebel Ali, Dammam, Hamburg)', max_length=200)),
                ('customs_notes', models.TextField(blank=True, default='', help_text='Special customs clearance certificates or importer requirements.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Export Country',
                'verbose_name_plural': 'Export Countries',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Commercial Invoice, Packing List, Certificate of Origin (Form A)', max_length=150, unique=True)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('purpose', models.TextField(help_text='Purpose of the document in customs clearance and international trade compliance.')),
                ('issuing_party', models.CharField(help_text='e.g., Exporter, Chamber of Commerce, Shipping Carrier, Notified Lab', max_length=150)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('sample_template', models.FileField(blank=True, null=True, upload_to='exports/templates/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Export Document',
                'verbose_name_plural': 'Export Documents',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoterm', models.CharField(choices=[('EXW', 'EXW — Ex Works'), ('FOB', 'FOB — Free On Board'), ('CFR', 'CFR — Cost and Freight'), ('CIF', 'CIF — Cost, Insurance and Freight'), ('DAP', 'DAP — Delivered At Place'), ('DDP', 'DDP — Delivered Duty Paid')], max_length=10, unique=True)),
                ('title', models.CharField(help_text='Descriptive title of the trade term', max_length=150)),
                ('buyer_responsibility', models.TextField(help_text='Clear breakdown of obligations, costs, and clearance borne by the buyer.')),
                ('seller_responsibility', models.TextField(help_text='Clear breakdown of exporter obligations (freight, packaging, port handling).')),
                ('risk_transfer_point', models.CharField(help_text='Exact physical juncture where risk of damage transfers to buyer.', max_length=200)),
                ('standard_ports_of_origin', models.CharField(default='Shanghai, Ningbo, Hamburg, Rotterdam, Jebel Ali', max_length=200)),
                ('estimated_transit_days', models.CharField(default='15 - 30 calendar days (Ocean Container)', max_length=100)),
                ('minimum_order', models.CharField(default='1x 20ft Container (approx. 280-320 kW) or 20 Inverter Units', max_length=150)),
                ('packaging_standard', models.TextField(default='Export heavy-duty reinforced wooden crates, moisture barrier vacuum film, corner edge protectors, tilt sensors.')),
                ('is_recommended', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Shipping Term & Incoterm',
                'verbose_name_plural': 'Shipping Terms & Incoterms',
                'ordering': ['sort_order', 'incoterm'],
            },
        ),
    ]
