# Generated by Django 6.1.1 on 2026-10-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='datasheet_pdf',
            field=models.FileField(blank=True, null=True, upload_to='products/datasheets/'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='power_watts',
            field=models.PositiveIntegerField(blank=True, help_text='Nominal power output in Watts (e.g. 550, 10000 for 10kW)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='technology_type',
            field=models.CharField(blank=True, default='', help_text='e.g. Mono PERC, Bifacial TopCon, LiFePO4, 3-Phase Hybrid', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_name',
            field=models.CharField(blank=True, default='sun', help_text='Icon identifier (e.g. sun, zap, battery, tool, droplet)', max_length=50),
        ),
    ]
