# Generated by Django 6.1.1 on 2026-10-04 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_product_datasheet_pdf_product_in_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., IEC 61215, UL 1741, CE EMC/LVD, ISO 9001', max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('category', models.CharField(choices=[('QUALITY', 'Quality Standards'), ('ELECTRICAL', 'Electrical Safety'), ('TESTING', 'Product Testing'), ('ENVIRONMENTAL', 'Environmental Compliance'), ('INTERNATIONAL', 'International Standards')], default='INTERNATIONAL', max_length=30)),
                ('issuing_body', models.CharField(help_text='e.g., TÜV Rheinland, UL Solutions, Intertek, ISO', max_length=150)),
                ('description', models.TextField(help_text='Detailed scope and testing requirements governed by this standard.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Compliance Standard',
                'verbose_name_plural': 'Compliance Standards',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(help_text='Official Certificate or Registration ID', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Official Certificate Title', max_length=200)),
                ('issuing_organization', models.CharField(help_text='Notified Testing Body (e.g., TÜV Rheinland Germany)', max_length=150)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='certifications/certificates/')),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, related_name='certifications', to='catalog.product')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='certifications.compliancestandard')),
            ],
            options={
                'verbose_name': 'Product Certification',
                'verbose_name_plural': 'Product Certifications',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=100, unique=True)),
                ('testing_laboratory', models.CharField(help_text='e.g., TÜV Rheinland Solar Lab, PVEL, UL Test Lab', max_length=150)),
                ('test_date', models.DateField()),
                ('test_type', models.CharField(help_text='e.g., PID Resistance Test, Hail 25mm Impact, Salt Mist Corrosion Class 6', max_length=150)),
                ('result', models.CharField(help_text='e.g., Passed - Power degradation < 1.1%', max_length=200)),
                ('status', models.CharField(choices=[('VERIFIED', 'Verified / Passed'), ('EXCEEDS', 'Exceeds Standard'), ('UNDER_REVIEW', 'Under Review')], default='VERIFIED', max_length=30)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='certifications/reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Laboratory Test Report',
                'verbose_name_plural': 'Laboratory Test Reports',
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_warranty_years', models.PositiveIntegerField(default=12, help_text='Material & Workmanship Warranty in Years')),
                ('performance_warranty_years', models.PositiveIntegerField(default=25, help_text='Linear Power Output Warranty in Years')),
                ('coverage_details', models.TextField(help_text='Detailed warranty provisions, replacement, or repair guarantees.')),
                ('exclusions', models.TextField(blank=True, default='', help_text='Acts of nature, improper installation, unapproved alterations.')),
                ('operating_conditions', models.TextField(blank=True, default='', help_text='Recommended operating temperature, humidity, and maintenance.')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='certifications/warranties/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warranty', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Warranty Term',
                'verbose_name_plural': 'Warranty Terms',
            },
        ),
    ]
